# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
